version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - '*'
    schedule:
      interval: 'weekly'
